### ISSUE TITLE
invalid compat entries

### ISSUE THREAD

**Issue by christopher-dG** [OpenLibMathSeq/IntegerTriangles.jl#2]
TagBot reported an error with your Project.toml and it's because your compat entries are not quoted (e.g. `Foo = 0.8.0` instead of `Foo = "0.8.0" `). If you fix that you should be able to get your pending registration automerged. 

 https://github.com/JuliaRegistries/TagBot/issues/103

**Comment by OpenLibMathSeq** [comment]
[noblock]
